NewBarkTown_MapScripts::
	.byte 0


NewBarkTown_Sign::
# 11 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Sign_Text_0
# 12 "data/maps/NewBarkTown/scripts.pory"
	release
	return


ElmsLaboratory_Sign::
# 16 "data/maps/NewBarkTown/scripts.pory"
	msgbox ElmsLaboratory_Sign_Text_0
# 17 "data/maps/NewBarkTown/scripts.pory"
	release
	return


PlayersHouse_Sign::
# 21 "data/maps/NewBarkTown/scripts.pory"
	msgbox PlayersHouse_Sign_Text_0
# 22 "data/maps/NewBarkTown/scripts.pory"
	release
	return


ProfElmsHouse_Sign::
# 26 "data/maps/NewBarkTown/scripts.pory"
	msgbox ProfElmsHouse_Sign_Text_0
# 27 "data/maps/NewBarkTown/scripts.pory"
	release
	return


RivalAtWindow::
# 31 "data/maps/NewBarkTown/scripts.pory"
	msgbox RivalAtWindow_Text_0
# 32 "data/maps/NewBarkTown/scripts.pory"
	release
	return


NewBarkTown_Sign_Text_0:
# 11 "data/maps/NewBarkTown/scripts.pory"
	.string "NEW BARK TOWN\n"
	.string "Winds of a New Beginning$"

ElmsLaboratory_Sign_Text_0:
# 16 "data/maps/NewBarkTown/scripts.pory"
	.string "Professor Elm's Pokemon Laboratory$"

PlayersHouse_Sign_Text_0:
# 21 "data/maps/NewBarkTown/scripts.pory"
	.string "{PLAYER}'s House$"

ProfElmsHouse_Sign_Text_0:
# 26 "data/maps/NewBarkTown/scripts.pory"
	.string "Professor Elm's House$"

RivalAtWindow_Text_0:
# 31 "data/maps/NewBarkTown/scripts.pory"
	.string "... ... ...\p"
	.string "So this is the famous Elm Laboratory...\p"
	.string "What are you staring at? Get lost!$"
