remote_theme: just-the-docs
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-default-layout

title: Joyful Johto
description: Making Johto a truly pleasant region
markdown: GFM