remote_theme: just-the-docs
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-default-layout

title: Joyful Johto
description: Making Johto a truly pleasant region
markdown: GFM

aux_links:
  "QOL Changes":
    - "//qol_changes"
  "Moves":
    - "//moves/moves"
  "Pokemon":
    - "//pokemon/main"
  "Routes and Cities":
    - "//routes/main"

nav_enabled: true